# Generated by Django 5.2.4 on 2025-07-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Укажите описание курса",
                null=True,
                verbose_name="Описание курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Укажите описание урока",
                null=True,
                verbose_name="Описание урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                help_text="Укажите название урока",
                max_length=35,
                unique=True,
                verbose_name="Название урока",
            ),
        ),
    ]
